# Generated by Django 3.2.7 on 2021-09-15 17:22

from django.db import migrations


# Generated by Django 3.2.7 on 2021-09-04 00:07

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME1 = 'exportBK.json'
DATA_FILENAME0 ='exportHL.json' 
DATA_FILENAME2 = 'exportRT.json'

def load_data(apps, schema_editor):
    Bank = apps.get_model('nearby','Bank')
    Restaurant = apps.get_model('nearby','Restaurant')
    Hotel = apps.get_model('nearby','Hotel')

    jsonfile0 = Path(__file__).parents[2]/DATA_FILENAME0
    jsonfile1 = Path(__file__).parents[2]/DATA_FILENAME1
    jsonfile2 = Path(__file__).parents[2]/DATA_FILENAME2

    with open(str(jsonfile0), encoding="utf8") as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon',0)
                    latitude = obj.get('lat',0)
                    location = fromstr(
                        f'POINT({longitude} {latitude})', srid=4326
                    )
                    Hotel(name=name, location=location).save()
            except KeyError:
                pass

    with open(str(jsonfile1), encoding="utf8") as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon',0)
                    latitude = obj.get('lat',0)
                    location = fromstr(
                        f'POINT({longitude} {latitude})', srid=4326
                    )
                    Bank(name=name, location=location).save()
            except KeyError:
                pass


    with open(str(jsonfile2), encoding="utf8") as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon',0)
                    latitude = obj.get('lat',0)
                    location = fromstr(
                        f'POINT({longitude} {latitude})', srid=4326
                    )
                    Restaurant(name=name, location=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('nearby', '0003_bank_hotel_restaurant'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
